"""Initial migration

Revision ID: 9d1a4c9ba618
Revises: 
Create Date: 2025-12-06 03:53:45.483035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d1a4c9ba618'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_identifier', sa.Text(), nullable=True),
    sa.Column('start_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_activity_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('message_count >= 0', name='message_count_positive'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_sessions_last_activity', 'chat_sessions', ['last_activity_timestamp'], unique=False, postgresql_ops={'last_activity_timestamp': 'DESC'})
    op.create_index('idx_sessions_user', 'chat_sessions', ['user_identifier'], unique=False, postgresql_where='user_identifier IS NOT NULL')
    op.create_table('user_queries',
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('selected_text', sa.Text(), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("(mode = 'full_book' AND selected_text IS NULL) OR (mode = 'selection' AND selected_text IS NOT NULL)", name='selected_text_required_for_selection'),
    sa.CheckConstraint("mode IN ('full_book', 'selection')", name='valid_mode'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_index('idx_queries_mode', 'user_queries', ['mode'], unique=False)
    op.create_index('idx_queries_session', 'user_queries', ['session_id', 'query_timestamp'], unique=False, postgresql_ops={'query_timestamp': 'DESC'})
    op.create_index('idx_queries_timestamp', 'user_queries', ['query_timestamp'], unique=False, postgresql_ops={'query_timestamp': 'DESC'})
    op.create_table('chat_responses',
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('source_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('response_time_ms > 0', name='response_time_positive'),
    sa.ForeignKeyConstraint(['query_id'], ['user_queries.query_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_index('idx_responses_query', 'chat_responses', ['query_id'], unique=False)
    op.create_index('idx_responses_time', 'chat_responses', ['response_time_ms'], unique=False)
    op.create_index('idx_responses_timestamp', 'chat_responses', ['generation_timestamp'], unique=False, postgresql_ops={'generation_timestamp': 'DESC'})
    op.create_table('user_feedback',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Text(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('feedback_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("rating IN ('positive', 'negative')", name='valid_rating'),
    sa.ForeignKeyConstraint(['response_id'], ['chat_responses.response_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id'),
    sa.UniqueConstraint('response_id')
    )
    op.create_index('idx_feedback_rating', 'user_feedback', ['rating'], unique=False)
    op.create_index('idx_feedback_response', 'user_feedback', ['response_id'], unique=False)
    op.create_index('idx_feedback_timestamp', 'user_feedback', ['feedback_timestamp'], unique=False, postgresql_ops={'feedback_timestamp': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_feedback_timestamp', table_name='user_feedback', postgresql_ops={'feedback_timestamp': 'DESC'})
    op.drop_index('idx_feedback_response', table_name='user_feedback')
    op.drop_index('idx_feedback_rating', table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_index('idx_responses_timestamp', table_name='chat_responses', postgresql_ops={'generation_timestamp': 'DESC'})
    op.drop_index('idx_responses_time', table_name='chat_responses')
    op.drop_index('idx_responses_query', table_name='chat_responses')
    op.drop_table('chat_responses')
    op.drop_index('idx_queries_timestamp', table_name='user_queries', postgresql_ops={'query_timestamp': 'DESC'})
    op.drop_index('idx_queries_session', table_name='user_queries', postgresql_ops={'query_timestamp': 'DESC'})
    op.drop_index('idx_queries_mode', table_name='user_queries')
    op.drop_table('user_queries')
    op.drop_index('idx_sessions_user', table_name='chat_sessions', postgresql_where='user_identifier IS NOT NULL')
    op.drop_index('idx_sessions_last_activity', table_name='chat_sessions', postgresql_ops={'last_activity_timestamp': 'DESC'})
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
